---
ai_context_version: 1.1

project:
  name: lenskit
  summary: RepoLens Merger & Scanner (epistemischer Kern) plus zugehörige Tooling-Skripte.
  role: merger_scanner_epistemic_core
  primary_language: bash
  visibility: internal

heimgewebe:
  axis: [Motorik]
  fleet:
    enabled: true
  wgx:
    profile_expected: false
    guard_smoke_expected: false

interfaces:
  consumes: ["CI/local shell"]
  produces: ["pinned binaries in tools/bin/*"]

boundaries:
  not_responsible_for:
    - "Project semantics; only tooling."

dependencies:
  internal: []
  external:
    - name: curl
    - name: bash
      version: ">=4"

architecture:
  entrypoints:
    - scripts/tools/*-pin.sh
  key_paths:
    - path: scripts/tools/yq-pin.sh
      purpose: Install/pin yq v4
  data_flow:
    input: CI & local setup
    processing: download/pin utilities
    output: tools/bin/*

conventions:
  branching: "main, feature/*"
  commit_prefix: "lenskit"
  ci_platform: github_actions

documentation:
  runbook: docs/runbook.md

ai_guidance:
  do:
    - fail fast on missing commands; provide actionable hints
  dont:
    - silently skip version mismatches
