import re

with open("merger/lenskit/tests/test_api_query.py", "r") as f:
    content = f.read()

# Replace test_api_query_review_context
new_review_context = """def test_api_query_review_context(mini_index):
    art = setup_test_artifact(mini_index)

    # First, test with context_window_lines to guarantee surrounding_context is generated
    request_data_with_context = {
        "index_id": art.id,
        "q": "hello",
        "k": 1,
        "context_mode": "window",
        "context_window_lines": 5,
        "output_profile": "review_context",
        "explain": True, "stale_policy": "ignore"
    }

    response = client.post("/api/query", json=request_data_with_context, headers={"Authorization": "Bearer test_token"})
    assert response.status_code == 200

    data = response.json()
    assert "hits" in data
    assert len(data["hits"]) > 0
    hit = data["hits"][0]

    # review_context should keep explain
    assert "explain" in hit
    # but strip graph_context
    assert "graph_context" not in hit
    # surrounding_context conditionally kept, and since we generated it, it MUST be here and not None
    assert "surrounding_context" in hit
    assert hit["surrounding_context"] is not None

    # Now, test WITHOUT context_window_lines to simulate surrounding_context = None scenario implicitly generated by the engine
    request_data_without_context = {
        "index_id": art.id,
        "q": "hello",
        "k": 1,
        "output_profile": "review_context",
        "explain": True, "stale_policy": "ignore"
    }

    response_no_ctx = client.post("/api/query", json=request_data_without_context, headers={"Authorization": "Bearer test_token"})
    assert response_no_ctx.status_code == 200

    data_no_ctx = response_no_ctx.json()
    hit_no_ctx = data_no_ctx["hits"][0]

    # If the engine drops it entirely or returns None, the profile MUST ensure it's removed or kept only if truthy.
    if "surrounding_context" in hit_no_ctx:
        assert hit_no_ctx["surrounding_context"] is not None
"""

content = re.sub(r'def test_api_query_review_context\(mini_index\):.*?(?=\n\n|\Z)', new_review_context, content, flags=re.DOTALL)

with open("merger/lenskit/tests/test_api_query.py", "w") as f:
    f.write(content)
