import pytest
import json
import jsonschema
from pathlib import Path
from merger.lenskit.core.merge import generate_json_sidecar

# Now targeting the correct sidecar schema
SCHEMA_PATH = Path(__file__).parents[1] / "contracts" / "repolens-agent.v2.schema.json"

@pytest.fixture
def schema():
    if not SCHEMA_PATH.exists():
        pytest.skip(f"Schema file not found at {SCHEMA_PATH}")
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

def test_sidecar_meta_validates_against_agent_schema(schema):
    """
    Verifies that the JSON sidecar generated by generate_json_sidecar
    complies with the repolens-agent.v2.schema.json.
    """
    # Use empty files list to avoid FileInfo fragility and focus on meta logic
    sidecar = generate_json_sidecar(
        files=[],
        level="summary",
        max_file_bytes=1000,
        sources=[Path("test_repo")],
        plan_only=False,
        requested_meta_density="auto"
    )

    # Validate the entire sidecar object directly against the correct schema
    jsonschema.validate(instance=sidecar, schema=schema)

    # Specific check: ensure requested_meta_density is present and correct in the meta block
    assert sidecar["meta"]["requested_meta_density"] == "auto"
    # effective should be "full" (default for auto without filters)
    assert sidecar["meta"]["meta_density"] == "full"

def test_sidecar_meta_validates_with_explicit_density(schema):
    """
    Verifies validation with explicit meta_density='min'.
    """
    sidecar = generate_json_sidecar(
        files=[],
        level="summary",
        max_file_bytes=1000,
        sources=[],
        plan_only=True,
        requested_meta_density="min"
    )

    jsonschema.validate(instance=sidecar, schema=schema)

    assert sidecar["meta"]["requested_meta_density"] == "min"
    assert sidecar["meta"]["meta_density"] == "min"
