import pytest
import json
import jsonschema
from pathlib import Path
from merger.lenskit.core.merge import generate_json_sidecar, FileInfo

SCHEMA_PATH = Path(__file__).parents[1] / "contracts" / "repolens-report.schema.json"

@pytest.fixture
def schema():
    if not SCHEMA_PATH.exists():
        pytest.skip(f"Schema file not found at {SCHEMA_PATH}")
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

def test_sidecar_meta_validates_against_report_schema(schema):
    """
    Verifies that the 'meta' block generated by generate_json_sidecar
    complies with the repolens-report.schema.json (which expects a 'merge' key).
    """
    # Create dummy file info
    files = [
        FileInfo(
            root_label="test_repo",
            abs_path=Path("/tmp/test.txt"),
            rel_path=Path("test.txt"),
            size=100,
            is_text=True,
            md5="a" * 32,
            category="source",
            tags=[],
            ext=".txt"
        )
    ]

    # Generate sidecar with requested_meta_density="auto"
    sidecar = generate_json_sidecar(
        files=files,
        level="summary",
        max_file_bytes=1000,
        sources=[Path("/tmp/test_repo")],
        plan_only=False,
        requested_meta_density="auto"
    )

    # The sidecar has a root 'meta' key. The schema expects a root 'merge' key.
    # Also, the sidecar uses contract="repolens-agent" but the schema enforces "repolens-report".
    # We patch the contract fields to validate the REST of the structure (meta_density etc).
    meta = sidecar["meta"]
    meta["contract"] = "repolens-report"
    meta["contract_version"] = "2.4"

    data_to_validate = {"merge": meta}

    # Verify strict schema compliance
    jsonschema.validate(instance=data_to_validate, schema=schema)

    # Specific check: ensure requested_meta_density is present and correct
    assert sidecar["meta"]["requested_meta_density"] == "auto"
    # effective should be "full" (default for auto without filters) or "standard"
    # (Here, no filters -> full)
    assert sidecar["meta"]["meta_density"] in ["min", "standard", "full"]

def test_sidecar_meta_validates_with_explicit_density(schema):
    """
    Verifies validation with explicit meta_density='min'.
    """
    sidecar = generate_json_sidecar(
        files=[],
        level="summary",
        max_file_bytes=1000,
        sources=[],
        plan_only=True,
        requested_meta_density="min"
    )

    meta = sidecar["meta"]
    meta["contract"] = "repolens-report"
    meta["contract_version"] = "2.4"

    data_to_validate = {"merge": meta}
    jsonschema.validate(instance=data_to_validate, schema=schema)

    assert sidecar["meta"]["requested_meta_density"] == "min"
    assert sidecar["meta"]["meta_density"] == "min"
