import pytest
import json
import jsonschema
from pathlib import Path
from merger.lenskit.core.merge import generate_json_sidecar, FileInfo

# Now targeting the correct sidecar schema
SCHEMA_PATH = Path(__file__).parents[1] / "contracts" / "repolens-agent.v2.schema.json"

@pytest.fixture
def schema():
    if not SCHEMA_PATH.exists():
        pytest.skip(f"Schema file not found at {SCHEMA_PATH}")
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

def test_sidecar_meta_validates_against_agent_schema(schema):
    """
    Verifies that the JSON sidecar generated by generate_json_sidecar
    complies with the repolens-agent.v2.schema.json.
    """
    # Create dummy file info
    files = [
        FileInfo(
            root_label="test_repo",
            abs_path=Path("/tmp/test.txt"),
            rel_path=Path("test.txt"),
            size=100,
            is_text=True,
            md5="a" * 32,
            category="source",
            tags=[],
            ext=".txt"
        )
    ]

    # Generate sidecar with requested_meta_density="auto"
    sidecar = generate_json_sidecar(
        files=files,
        level="summary",
        max_file_bytes=1000,
        sources=[Path("/tmp/test_repo")],
        plan_only=False,
        requested_meta_density="auto"
    )

    # Validate the entire sidecar object directly against the correct schema
    jsonschema.validate(instance=sidecar, schema=schema)

    # Specific check: ensure requested_meta_density is present and correct in the meta block
    assert sidecar["meta"]["requested_meta_density"] == "auto"
    # effective should be "full" (default for auto without filters) or "standard"
    assert sidecar["meta"]["meta_density"] in ["min", "standard", "full"]

def test_sidecar_meta_validates_with_explicit_density(schema):
    """
    Verifies validation with explicit meta_density='min'.
    """
    sidecar = generate_json_sidecar(
        files=[],
        level="summary",
        max_file_bytes=1000,
        sources=[],
        plan_only=True,
        requested_meta_density="min"
    )

    jsonschema.validate(instance=sidecar, schema=schema)

    assert sidecar["meta"]["requested_meta_density"] == "min"
    assert sidecar["meta"]["meta_density"] == "min"
